### ISSUE TITLE
upgrade should be optional

### ISSUE THREAD

**Issue by 030** [Ilyes512/ansible-role-base#1]
upgrading by default could brake the system
force could be very dangerous

```
- name: Upgrade apt-packages
  become: yes
  apt:
    upgrade: "{{ base_upgrade_packages }}"
    force: "{{ base_force_upgrade_packages }}"
    update_cache: yes
    cache_valid_time: 3600
```
